name: Generate SBOM 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
   

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install CycloneDX CLI
        run: npm install --save-dev @cyclonedx/bom

      - name: Generate SBOM file
        run: npx cyclonedx-bom -o bom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-react
          path: bom.json

      - name: Upload SBOM to Dependency-Track
        env:
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
          DTRACK_API_URL: "http://localhost:8080"
        run: |
          curl -X POST "$DTRACK_API_URL/api/v1/bom" \
            -H "X-Api-Key: $DTRACK_API_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @bom.json
     
